import { DanishNumber } from './numbers.interface';

export const danishNumbers: DanishNumber[] = [
  { number: 0, name: 'nul	' },
  { number: 1, name: 'en (et)' },
  { number: 2, name: 'to' },
  { number: 3, name: 'tre' },
  { number: 4, name: 'fire' },
  { number: 5, name: 'fem' },
  { number: 6, name: 'seks' },
  { number: 7, name: 'syv' },
  { number: 8, name: 'otte' },
  { number: 9, name: 'ni' },
  { number: 10, name: 'ti' },
  { number: 11, name: 'elleve' },
  { number: 12, name: 'tolv' },
  { number: 13, name: 'tretten' },
  { number: 14, name: 'fjorten' },
  { number: 15, name: 'femten' },
  { number: 16, name: 'seksten' },
  { number: 17, name: 'sytten' },
  { number: 18, name: 'atten' },
  { number: 19, name: 'nitten' },
  { number: 20, name: 'tyve' },
  { number: 21, name: 'enogtyve' },
  { number: 22, name: 'toogtyve' },
  { number: 23, name: 'treogtyve' },
  { number: 24, name: 'fireogtyve	' },
  { number: 25, name: 'femogtyve' },
  { number: 26, name: 'seksogtyve	' },
  { number: 27, name: 'syvogtyve' },
  { number: 28, name: 'otteogtyve	' },
  { number: 29, name: 'niogtyve' },
  { number: 30, name: 'tredive' },
  { number: 31, name: 'enogtredive' },
  { number: 32, name: 'toogtredive' },
  { number: 33, name: 'treogtredive' },
  { number: 34, name: 'fireogtredive' },
  { number: 35, name: 'femogtredive' },
  { number: 36, name: 'seksogtredive' },
  { number: 37, name: 'syvogtredive' },
  { number: 38, name: 'otteogtredive' },
  { number: 39, name: 'niogtredive' },
  { number: 40, name: 'fyrre' },
  { number: 41, name: 'enogfyrre' },
  { number: 42, name: 'toogfyrre' },
  { number: 43, name: 'treogfyrre' },
  { number: 44, name: 'fireogfyrre' },
  { number: 45, name: 'femogfyrre' },
  { number: 46, name: 'seksogfyrre' },
  { number: 47, name: 'syvogfyrre' },
  { number: 48, name: 'otteogfyrre' },
  { number: 49, name: 'niogfyrre' },
  { number: 50, name: 'halvtreds' },
  { number: 51, name: 'enoghalvtreds' },
  { number: 52, name: 'tooghalvtreds' },
  { number: 53, name: 'treoghalvtreds' },
  { number: 54, name: 'fireoghalvtreds' },
  { number: 55, name: 'femoghalvtreds' },
  { number: 56, name: 'seksoghalvtreds' },
  { number: 57, name: 'syvoghalvtreds' },
  { number: 58, name: 'otteoghalvtreds' },
  { number: 59, name: 'nioghalvtreds' },
  { number: 60, name: 'tres' },
  { number: 61, name: 'enogtres' },
  { number: 62, name: 'toogtres' },
  { number: 63, name: 'treogtres' },
  { number: 64, name: 'fireogtres' },
  { number: 65, name: 'femogtres' },
  { number: 66, name: 'seksogtres	' },
  { number: 67, name: 'syvogtres' },
  { number: 68, name: 'otteogtres' },
  { number: 69, name: 'niogtres' },
  { number: 70, name: 'halvfjerds' },
  { number: 71, name: 'enoghalvfjerds' },
  { number: 72, name: 'tooghalvfjerds' },
  { number: 73, name: 'treoghalvfjerds' },
  { number: 74, name: 'fireoghalvfjerds' },
  { number: 75, name: 'femoghalvfjerds' },
  { number: 76, name: 'seksoghalvfjerds' },
  { number: 77, name: 'syvoghalvfjerds' },
  { number: 78, name: 'otteoghalvfjerds' },
  { number: 79, name: 'nioghalvfjerds' },
  { number: 80, name: 'firs' },
  { number: 81, name: 'enogfirs' },
  { number: 82, name: 'toogfirs' },
  { number: 83, name: 'treogfirs' },
  { number: 84, name: 'fireogfirs' },
  { number: 85, name: 'femogfirs' },
  { number: 86, name: 'seksogfirs' },
  { number: 87, name: 'syvogfirs' },
  { number: 88, name: 'otteogfirs' },
  { number: 89, name: 'niogfirs' },
  { number: 90, name: 'halvfems' },
  { number: 91, name: 'enoghalvfems' },
  { number: 92, name: 'tooghalvfems' },
  { number: 93, name: 'treoghalvfems' },
  { number: 94, name: 'fireoghalvfems' },
  { number: 95, name: 'femoghalvfems' },
  { number: 96, name: 'seksoghalvfems' },
  { number: 97, name: 'syvoghalvfems' },
  { number: 98, name: 'otteoghalvfems' },
  { number: 99, name: 'nioghalvfems' },
  { number: 100, name: 'et hundrede' },
];

export const placeNumbers: DanishNumber[] = [
  { number: 100, name: 'hundrede', gender: 'et' },
  { number: 1000, name: 'tusind', gender: 'et' },
  { number: 1000000, name: 'million', gender: 'en' },
  { number: 1000000000, name: 'milliard', gender: 'en' },
];

/**
 * an array of indicies to be used with placeNumbers in order to build the danish string,
 * contains -1, 0, 1, 2 for values.
 * -1 means use the danishNumbers array for 2 digits and placement.
 * For example '5' would be used to build femogtredive tusind tre hundrede og femogfyrre
 */
export const placeNumbersIndexing: any = {
  '3': [0, -1], // 100 - 1000
  '4': [1, 0, -1], // 1000 - 10 000
  '5': [-1, 1, 0, -1], // this one is convoluted -> eg 54 thousand
  '6': [0, -1, 1, 0, -1], // 100 000 - 1 000 000
  '7': [2, 0, -1, 1, 0, -1], // 1 000 000 - 10 000 000
};
