import { DanishNumber, DanishNumberDict } from './numbers.interface';

export const danishNumbers: DanishNumber[] = [
  { number: 0, name: 'nul	' },
  { number: 1, name: 'en', gender: 'en (et)' },
  { number: 2, name: 'to' },
  { number: 3, name: 'tre' },
  { number: 4, name: 'fire' },
  { number: 5, name: 'fem' },
  { number: 6, name: 'seks' },
  { number: 7, name: 'syv' },
  { number: 8, name: 'otte' },
  { number: 9, name: 'ni' },
  { number: 10, name: 'ti' },
  { number: 11, name: 'elleve' },
  { number: 12, name: 'tolv' },
  { number: 13, name: 'tretten' },
  { number: 14, name: 'fjorten' },
  { number: 15, name: 'femten' },
  { number: 16, name: 'seksten' },
  { number: 17, name: 'sytten' },
  { number: 18, name: 'atten' },
  { number: 19, name: 'nitten' },
  { number: 20, name: 'tyve' },
  { number: 21, name: 'enogtyve' },
  { number: 22, name: 'toogtyve' },
  { number: 23, name: 'treogtyve' },
  { number: 24, name: 'fireogtyve	' },
  { number: 25, name: 'femogtyve' },
  { number: 26, name: 'seksogtyve	' },
  { number: 27, name: 'syvogtyve' },
  { number: 28, name: 'otteogtyve	' },
  { number: 29, name: 'niogtyve' },
  { number: 30, name: 'tredive' },
  { number: 31, name: 'enogtredive' },
  { number: 32, name: 'toogtredive' },
  { number: 33, name: 'treogtredive' },
  { number: 34, name: 'fireogtredive' },
  { number: 35, name: 'femogtredive' },
  { number: 36, name: 'seksogtredive' },
  { number: 37, name: 'syvogtredive' },
  { number: 38, name: 'otteogtredive' },
  { number: 39, name: 'niogtredive' },
  { number: 40, name: 'fyrre' },
  { number: 41, name: 'enogfyrre' },
  { number: 42, name: 'toogfyrre' },
  { number: 43, name: 'treogfyrre' },
  { number: 44, name: 'fireogfyrre' },
  { number: 45, name: 'femogfyrre' },
  { number: 46, name: 'seksogfyrre' },
  { number: 47, name: 'syvogfyrre' },
  { number: 48, name: 'otteogfyrre' },
  { number: 49, name: 'niogfyrre' },
  { number: 50, name: 'halvtreds' },
  { number: 51, name: 'enoghalvtreds' },
  { number: 52, name: 'tooghalvtreds' },
  { number: 53, name: 'treoghalvtreds' },
  { number: 54, name: 'fireoghalvtreds' },
  { number: 55, name: 'femoghalvtreds' },
  { number: 56, name: 'seksoghalvtreds' },
  { number: 57, name: 'syvoghalvtreds' },
  { number: 58, name: 'otteoghalvtreds' },
  { number: 59, name: 'nioghalvtreds' },
  { number: 60, name: 'tres' },
  { number: 61, name: 'enogtres' },
  { number: 62, name: 'toogtres' },
  { number: 63, name: 'treogtres' },
  { number: 64, name: 'fireogtres' },
  { number: 65, name: 'femogtres' },
  { number: 66, name: 'seksogtres	' },
  { number: 67, name: 'syvogtres' },
  { number: 68, name: 'otteogtres' },
  { number: 69, name: 'niogtres' },
  { number: 70, name: 'halvfjerds' },
  { number: 71, name: 'enoghalvfjerds' },
  { number: 72, name: 'tooghalvfjerds' },
  { number: 73, name: 'treoghalvfjerds' },
  { number: 74, name: 'fireoghalvfjerds' },
  { number: 75, name: 'femoghalvfjerds' },
  { number: 76, name: 'seksoghalvfjerds' },
  { number: 77, name: 'syvoghalvfjerds' },
  { number: 78, name: 'otteoghalvfjerds' },
  { number: 79, name: 'nioghalvfjerds' },
  { number: 80, name: 'firs' },
  { number: 81, name: 'enogfirs' },
  { number: 82, name: 'toogfirs' },
  { number: 83, name: 'treogfirs' },
  { number: 84, name: 'fireogfirs' },
  { number: 85, name: 'femogfirs' },
  { number: 86, name: 'seksogfirs' },
  { number: 87, name: 'syvogfirs' },
  { number: 88, name: 'otteogfirs' },
  { number: 89, name: 'niogfirs' },
  { number: 90, name: 'halvfems' },
  { number: 91, name: 'enoghalvfems' },
  { number: 92, name: 'tooghalvfems' },
  { number: 93, name: 'treoghalvfems' },
  { number: 94, name: 'fireoghalvfems' },
  { number: 95, name: 'femoghalvfems' },
  { number: 96, name: 'seksoghalvfems' },
  { number: 97, name: 'syvoghalvfems' },
  { number: 98, name: 'otteoghalvfems' },
  { number: 99, name: 'nioghalvfems' },
  { number: 100, name: 'et hundrede' },
];

export const danishNumberDict: DanishNumberDict = {
  0: { number: 0, name: 'nul	' },
  1: { number: 1, name: 'en (et)' },
  2: { number: 2, name: 'to' },
  3: { number: 3, name: 'tre' },
  4: { number: 4, name: 'fire' },
  5: { number: 5, name: 'fem' },
  6: { number: 6, name: 'seks' },
  7: { number: 7, name: 'syv' },
  8: { number: 8, name: 'otte' },
  9: { number: 9, name: 'ni' },
  10: { number: 10, name: 'ti' },
  11: { number: 11, name: 'elleve' },
  12: { number: 12, name: 'tolv' },
  13: { number: 13, name: 'tretten' },
  14: { number: 14, name: 'fjorten' },
  15: { number: 15, name: 'femten' },
  16: { number: 16, name: 'seksten' },
  17: { number: 17, name: 'sytten' },
  18: { number: 18, name: 'atten' },
  19: { number: 19, name: 'nitten' },
  20: { number: 20, name: 'tyve' },
  21: { number: 21, name: 'enogtyve' },
  22: { number: 22, name: 'toogtyve' },
  23: { number: 23, name: 'treogtyve' },
  24: { number: 24, name: 'fireogtyve	' },
  25: { number: 25, name: 'femogtyve' },
  26: { number: 26, name: 'seksogtyve	' },
  27: { number: 27, name: 'syvogtyve' },
  28: { number: 28, name: 'otteogtyve	' },
  29: { number: 29, name: 'niogtyve' },
  30: { number: 30, name: 'tredive' },
  31: { number: 31, name: 'enogtredive' },
  32: { number: 32, name: 'toogtredive' },
  33: { number: 33, name: 'treogtredive' },
  34: { number: 34, name: 'fireogtredive' },
  35: { number: 35, name: 'femogtredive' },
  36: { number: 36, name: 'seksogtredive' },
  37: { number: 37, name: 'syvogtredive' },
  38: { number: 38, name: 'otteogtredive' },
  39: { number: 39, name: 'niogtredive' },
  40: { number: 40, name: 'fyrre' },
  41: { number: 41, name: 'enogfyrre' },
  42: { number: 42, name: 'toogfyrre' },
  43: { number: 43, name: 'treogfyrre' },
  44: { number: 44, name: 'fireogfyrre' },
  45: { number: 45, name: 'femogfyrre' },
  46: { number: 46, name: 'seksogfyrre' },
  47: { number: 47, name: 'syvogfyrre' },
  48: { number: 48, name: 'otteogfyrre' },
  49: { number: 49, name: 'niogfyrre' },
  50: { number: 50, name: 'halvtreds' },
  51: { number: 51, name: 'enoghalvtreds' },
  52: { number: 52, name: 'tooghalvtreds' },
  53: { number: 53, name: 'treoghalvtreds' },
  54: { number: 54, name: 'fireoghalvtreds' },
  55: { number: 55, name: 'femoghalvtreds' },
  56: { number: 56, name: 'seksoghalvtreds' },
  57: { number: 57, name: 'syvoghalvtreds' },
  58: { number: 58, name: 'otteoghalvtreds' },
  59: { number: 59, name: 'nioghalvtreds' },
  60: { number: 60, name: 'tres' },
  61: { number: 61, name: 'enogtres' },
  62: { number: 62, name: 'toogtres' },
  63: { number: 63, name: 'treogtres' },
  64: { number: 64, name: 'fireogtres' },
  65: { number: 65, name: 'femogtres' },
  66: { number: 66, name: 'seksogtres	' },
  67: { number: 67, name: 'syvogtres' },
  68: { number: 68, name: 'otteogtres' },
  69: { number: 69, name: 'niogtres' },
  70: { number: 70, name: 'halvfjerds' },
  71: { number: 71, name: 'enoghalvfjerds' },
  72: { number: 72, name: 'tooghalvfjerds' },
  73: { number: 73, name: 'treoghalvfjerds' },
  74: { number: 74, name: 'fireoghalvfjerds' },
  75: { number: 75, name: 'femoghalvfjerds' },
  76: { number: 76, name: 'seksoghalvfjerds' },
  77: { number: 77, name: 'syvoghalvfjerds' },
  78: { number: 78, name: 'otteoghalvfjerds' },
  79: { number: 79, name: 'nioghalvfjerds' },
  80: { number: 80, name: 'firs' },
  81: { number: 81, name: 'enogfirs' },
  82: { number: 82, name: 'toogfirs' },
  83: { number: 83, name: 'treogfirs' },
  84: { number: 84, name: 'fireogfirs' },
  85: { number: 85, name: 'femogfirs' },
  86: { number: 86, name: 'seksogfirs' },
  87: { number: 87, name: 'syvogfirs' },
  88: { number: 88, name: 'otteogfirs' },
  89: { number: 89, name: 'niogfirs' },
  90: { number: 90, name: 'halvfems' },
  91: { number: 91, name: 'enoghalvfems' },
  92: { number: 92, name: 'tooghalvfems' },
  93: { number: 93, name: 'treoghalvfems' },
  94: { number: 94, name: 'fireoghalvfems' },
  95: { number: 95, name: 'femoghalvfems' },
  96: { number: 96, name: 'seksoghalvfems' },
  97: { number: 97, name: 'syvoghalvfems' },
  98: { number: 98, name: 'otteoghalvfems' },
  99: { number: 99, name: 'nioghalvfems' },
  100: { number: 100, name: 'hundrede', gender: 'et' },
  1000: { number: 1000, name: 'tusind', gender: 'et' },
  1000000: { number: 1000000, name: 'million', gender: 'en' },
  1000000000: { number: 1000000000, name: 'milliard', gender: 'en' },
};
